@endpoint = http://localhost:3000

### GET /api/aircrafts
GET {{endpoint}}/api/aircrafts HTTP/1.1
content-type: application/json

### GET /api/aircrafts (on sale)
GET {{endpoint}}/api/aircrafts?airline=none HTTP/1.1
content-type: application/json

### GET /api/aircrafts (mine)
GET {{endpoint}}/api/aircrafts?airline=5b5edb8078200e322c5667f2 HTTP/1.1
content-type: application/json

### GET /api/aircrafts (other airlines)
GET {{endpoint}}/api/aircrafts?airline=!5b5edb8078200e322c5667f2 HTTP/1.1
content-type: application/json

### GET /api/aircrafts/{id}
GET {{endpoint}}/api/aircrafts/64de5416482fbf12a863d56f HTTP/1.1
content-type: application/json

### POST /api/aircrafts/{id}
POST {{endpoint}}/api/aircrafts/64de5416482fbf12a863d56f HTTP/1.1
content-type: application/json

{
  "userId": "5b5edb8078200e322c5667f2"
}

### DELETE /api/aircrafts/{id}
DELETE {{endpoint}}/api/aircrafts/64de5416482fbf12a863d56f HTTP/1.1
content-type: application/json

{
  "userId": "5b5edb8078200e322c5667f2"
}
