@endpoint = http://localhost:3000

### GET /api/aircrafts
GET {{endpoint}}/api/aircrafts HTTP/1.1
content-type: application/json

### GET /api/aircrafts (on sale)
GET {{endpoint}}/api/aircrafts?airline=none HTTP/1.1
content-type: application/json

### GET /api/aircrafts (mine)
GET {{endpoint}}/api/aircrafts?airline=5b5edb8078200e322c5667f2 HTTP/1.1
content-type: application/json

### GET /api/aircrafts (other airlines)
GET {{endpoint}}/api/aircrafts?airline=!5b5edb8078200e322c5667f2 HTTP/1.1
content-type: application/json

### GET /api/aircrafts/{id}
GET {{endpoint}}/api/aircrafts/64d513e5a749f7514f1557b5 HTTP/1.1
content-type: application/json

### POST /api/aircrafts/{id}/{userId}
POST {{endpoint}}/api/aircrafts/64d513e5a749f7514f1557b5 HTTP/1.1
content-type: application/json

{
  "userId": "64d51498a749f7514f1557b7"
}
